### ISSUE TITLE
Cannot find temporary .mat when converting on Windows

### ISSUE THREAD

**Issue by agricolab** [translationalneurosurgery/tool-load-tms#1]
see https://github.com/translationalneurosurgery/tool-offspect/issues/11

**Comment by agricolab** [comment]
I think there are two solutions i would try. The first is to return a less troublesome temporary folder, maybe 
``` python
if "win" in sys.platform:
   self.tmpdir  = Path(__file__).parent.expanduser().absolute() / "tmp"
   self.tmpdir.mkdir(parents=True exist_ok=True)
else:
    self.tmpdir = Path(mkdtemp()).expanduser().absolute()
```
at https://github.com/translationalneurosurgery/tool-load-tms/blob/master/matprot/convert/traces.py#L24

**Comment by agricolab** [comment]
Please be aware that every directory created with mkdtemp needs to be deleted by the user, and we do so here: https://github.com/translationalneurosurgery/tool-load-tms/blob/master/matprot/convert/traces.py#L32, so make sure you do not use an important folder as temporary folder!

**Comment by ethanrich** [comment]
Encountering an error in matlab after calling subprocess.run
![SharedScreenshot](https://user-images.githubusercontent.com/48725637/77426785-7ebd0580-6dd5-11ea-9c9a-fd019ce4ff47.jpg)

**Comment by ethanrich** [comment]
`content = loadmat(tmpdir.matfile)`
returns `OSError: Reader needs file name or open file-like object`

`content = loadmat(r'C:\Users\ethan\AppData\Local\Temp\tmpqwr6t2p5\conversion.mat')`
returns `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ethan\\AppData\\Local\\Temp\\tmpqwr6t2p5\\conversion.mat'`

However, `content = loadmat(r'C:\Users\ethan\data.mat')` returns the data from the mat file.

**Comment by agricolab** [comment]
> content = loadmat(r'C:\Users\ethan\data.mat') 
is this a copy of the conversion.mat or a different file?

**Comment by ethanrich** [comment]
It's from `convert_mat`

https://github.com/translationalneurosurgery/tool-load-tms/blob/master/matprot/convert/traces.py#L104

**Comment by agricolab** [comment]
So we create a new `.m`file depending on the raw `.mat`-file to be loaded following this template: https://github.com/translationalneurosurgery/tool-load-tms/blob/master/matprot/convert/traces.py#L62

**Comment by agricolab** [comment]
Do you think that replacing all `"` with `'` in the template would work?

**Comment by ethanrich** [comment]
Just tried. Still results in formatting.
![Capture](https://user-images.githubusercontent.com/48725637/77429464-fb51e300-6dd9-11ea-95e4-631417ce1414.PNG)

**Comment by agricolab** [comment]
try `\' `

**Comment by ethanrich** [comment]
No change.

**Comment by agricolab** [comment]
f.write(content) instead of print(content, file=f)?

**Comment by ethanrich** [comment]
`\'` successful when only added to `addpath(\'{addpath}\')` 

Content successfully loaded and no matlab command prompt errors thrown.

**Comment by ethanrich** [comment]
Function reads as 
`def create_matlab_commands(matfile: FileName) -> Path:
    """create an mfile to convert the object in a matfile

    args
    ----
    fname:str
        the path to the :code:`.mat`-file 

    returns
    -------
    mfile: Path
        the path to the mfile 

    this matlab code would load the object and save it as simpler .mat-file readable with python
    """
    template = """
    addpath(\'{addpath}\')
    [data, fs, chan_names, stim_onset, stim_code, mso, subid, recdate] = load_all(\'{fname}\');
    save(\'{savefile}\', 'data', 'fs', 'chan_names', 'stim_onset', 'stim_code', 'mso', 'subid', 'recdate');
    """
    matfile = Path(matfile).expanduser().absolute()
    if not matfile.exists():
        raise FileNotFoundError(f"{matfile} not found")
    addpath = str(Path(__file__).parent.parent / "ml")
    content = template.format(addpath=addpath, fname=matfile, savefile=tmpdir.matfile)
    tmpdir.refresh()
    with tmpdir.mfile.open("w") as f:
        print(content, file=f)
    return tmpdir.mfile`

**Comment by agricolab** [comment]
Hopefully fixed by https://github.com/translationalneurosurgery/tool-load-tms/commit/549a27ec93cdf84fee23b04a13aea806bc27c668

**Comment by agricolab** [comment]
Might also be linked to the deprecation of `-r` in the matlab cli. Additionally,  matlab startup is different between linux https://de.mathworks.com/help/matlab/ref/matlablinux.html and windows https://de.mathworks.com/help/matlab/ref/matlabwindows.html
Seems the -wait was added and since  2019a, -r is deprecated in favor of -batch. We could try the following template shell command
```    
command = "-batch \"run('{mfile}'); exit;\""
commands = [
        "matlab",
        "-wait",
        "-nodesktop",
        "-nosplash",
        "-nodisplay",
        command.format(mfile=mfile),
    ]
```

**Comment by ethanrich** [comment]
Added a conditional to check for the system in `create_shell_commands `so that on windows, there are no extra slashes, which throw a matlab error. 

However, `subprocess.run`  in `convert_mat ` now opens the matlab command prompt, which waits for input. If the command `run('C:\\Users\\ethan\\AppData\\Local\\Temp\\tmpnfhtayll\\conversion.m');` is entered, a matfile is successfully created and can be loaded. 

Additionally, `subprocess.Popen` followed by `communicate()` also opens a command prompt and waits for input. 

Lastly, if only the commands `"matlab" + run(<filepath>)` are passed to `subprocess.run`, produces the same lack of conversion.

**Comment by ethanrich** [comment]
Added another conditional to check for system in `convert_mat `so that in windows this executes: `subprocess.run(commands)`

This results in successful conversion of the mat file and passes pytest. However, the user must either close the matlab command prompt or type `exit` and hit enter.

**Comment by agricolab** [comment]
The point of the `-r "run(mfile);"` was to pass code to be executed by the matlab prompt.  With Matlab2019a, they use `-r` apparently for interactive workflows? See https://de.mathworks.com/help/matlab/ref/matlabwindows.html
![image](https://user-images.githubusercontent.com/20556511/77538503-230b7e80-6ea0-11ea-8ac5-a54fb630eb81.png)
So, would it work with using `-batch` instead of `-r`, i.e. would it close the console again?

**Comment by ethanrich** [comment]
Changing `-r "run(mfile);"` to `-batch "run(mfile);"` corresponds with the pytest error:
![SharedScreenshot](https://user-images.githubusercontent.com/48725637/77539020-f441d800-6ea0-11ea-96a8-9cd09c572883.jpg)

**Comment by agricolab** [comment]
that's why i suggested to also add`-wait`, as mentioned above https://github.com/translationalneurosurgery/tool-load-tms/issues/1#issuecomment-603441606

**Comment by ethanrich** [comment]
Yes, that suggestion is currently in use.

**Comment by agricolab** [comment]
When we `" ".join()`, does this remove the `"` and create an invalid shell command?

**Comment by ethanrich** [comment]
It doesn't look like it. 
![SharedScreenshot](https://user-images.githubusercontent.com/48725637/77540686-d3c74d00-6ea3-11ea-8fbf-dab4f9cd68d4.jpg)

**Comment by agricolab** [comment]
> statement is MATLAB code enclosed in double quotation marks.  
Yet, your output in line 4 shows that following `-batch`, the statement is  not wrapped in double quotation marks.

**Comment by ethanrich** [comment]
The statement wrapped in double quotation marks still opens the matlab command prompt and does not produce a mat file.

**Comment by agricolab** [comment]
And it does not execute any of the code in *statement* ?

**Comment by ethanrich** [comment]
I've tried removing all flags, as well as only including each one

**Comment by agricolab** [comment]
If you dont use subprocess.run to start the command, but use the same command directly from the windows prompt, does it work?

**Comment by ethanrich** [comment]
With `-batch`  the matlab command prompt opens but a mat file is not produced.

**Comment by agricolab** [comment]
Fixed in https://github.com/translationalneurosurgery/tool-load-tms/commit/0bf24c87aaca2f6f4d42d305f3a5d0d361c521de by escaping the `"` and `'` and adding an `exit;` at the end of the mfile.
